<?php
$title = 'Editează procedură';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'procedures',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('pro_id'));
echo "<div class=\"form-group\">";
echo $this->formLabel($form->get('pro_procedure_name'));
echo $this->formInput($form->get('pro_procedure_name'));
echo $this->formElementErrors($form->get('pro_procedure_name'));
echo "</div>";
echo "<div class=\"form-group\">";
echo $this->formLabel($form->get('pro_normal_duration'));
echo $this->formInput($form->get('pro_normal_duration'));
echo $this->formElementErrors($form->get('pro_normal_duration'));
echo "</div>";
echo "<div class=\"form-group\">";
echo $this->formLabel($form->get('pro_priority'));
echo $this->formInput($form->get('pro_priority'));
echo $this->formElementErrors($form->get('pro_priority'));
echo "</div>";
echo "<div class=\"form-group\">";
echo $this->formLabel($form->get('pro_pat_number'));
echo $this->formInput($form->get('pro_pat_number'));
echo $this->formElementErrors($form->get('pro_pat_number'));
echo "</div>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();