<?php 
$title = 'Șterge date pacient';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Ești sigur că vrei să ștergi datele pacientului 
    <?php echo $this->escapeHtml($patients->pat_lastname); ?> 
    <?php echo $this->escapeHtml($patients->pat_firstname); ?>?
</p>
<?php
$url = $this->url('patients', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="pat_id" value="<?php echo (int) $patients->pat_id; ?>" />
    <input type="submit" name="del" value="Da" class="btn btn-default" />
    <input type="submit" name="del" value="Nu" class="btn btn-default" />
</div>
</form>