<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="robots" content="noindex, nofollow">
        <?php echo $this->headTitle(/*'ZF2 '.*/ $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
								      ->prependFile($this->basePath() . '/js/auxiliary.js')
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
            	      <div class="navbar-header">
				        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				          <span class="sr-only">Toggle navigation</span>
				          <span class="icon-bar"></span>
				          <span class="icon-bar"></span>
				          <span class="icon-bar"></span>
				        </button>
                    <a class="navbar-brand" href="<?php echo $this->url('appointments') ?>">&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                    </div>
                    <?php 
 						echo $this->navigation('navigation')
						           ->menu()
						           ->setMinDepth(0)
						           ->setMaxDepth(0)
						           ->setUlClass('nav navbar-nav');
 					?>
                    <?php 
                    	if($this->zfcUserIdentity()):
                    ?>
	                    <ul class="nav navbar-nav">
	                    	<li><a href="<?php echo $this->url('zfcuser/logout'); ?>">Logout</a></li>
	                    </ul>
	                <?php 
	                	endif;
	                ?>
            </div>
        </div>
        <div class="container">
        	<?php echo $this->navigation('navigation') 
               ->breadcrumbs()
               ->setMinDepth(0)
               ->setPartial(array('partial/breadcrumb.phtml', 'Fiziomed')); ?>
            <?php echo $this->content; ?>
            <hr>
            <!-- 
            <footer>
                <p>&copy; 2005 - <?php // echo date('Y') ?> by Zend Technologies Ltd. <?php //echo $this->translate('All rights reserved.') ?></p>
            </footer>
 			-->
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
